CREATE PROC FI_SP_PesqBeneficiario
	@IDCLIENTE INT

AS
BEGIN
	DECLARE @SCRIPT NVARCHAR(MAX)
	DECLARE @CAMPOS NVARCHAR(MAX)

	SET @CAMPOS = '@IDCLIENTE'
	SET @SCRIPT = 
	'SELECT ID, CPF, NOME, IDCLIENTE FROM BENEFICIARIOS 
	WHERE IDCLIENTE = @IDCLIENTE
	ORDER BY ID'


	EXECUTE SP_EXECUTESQL @SCRIPT, @CAMPOS

	SELECT COUNT(1) FROM BENEFICIARIOS WITH(NOLOCK)
END